name: Set imgpkg bundle as vendir path
description: Sets an imgpkg bundle image as a vendir path.

inputs:
  channel_name:
    description: The path under the channels directory to update.
    required: true
  imgpkg_bundle_image:
    description: The imgpkg bundle image.
    required: true
  bearer_token:
    description: Optional bearer token for authentication.
    required: false
  path:
    description: The base directory path where vendir.yml is located.
    required: false
    default: '.'

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.channel_name }}
    - ${{ inputs.imgpkg_bundle_image }}
    - ${{ inputs.bearer_token }}
    - ${{ inputs.path }}
