name: Next Image Tag Number
description: Get the next tag number for an image in an OCI repository.

inputs:
  repository_api_url:
    description: The full URL of the OCI-compatible repository API.
    required: true
  image:
    description: The name of the image within the specified repository.
    required: true
  bearer_token:
    description: Optional bearer token for authentication.
    required: false
  initial_number:
    description: Starting tag number if no tags exist.
    default: '1'
    required: false
  tag_prefix:
    description: Prefix for the tags.
    default: 'build-'
    required: false

outputs:
  tag:
    description: The next tag, including the prefix and tag number.
  number:
    description: The next tag number.

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.repository_api_url }}
    - ${{ inputs.image }}
    - ${{ inputs.bearer_token }}
    - ${{ inputs.initial_number }}
    - ${{ inputs.tag_prefix }}
