name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  validate-changelog:
    name: Validate Changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate Changelog
        uses: denisa/clq-action@v1
        with:
          changeMap: .github/clq/changemap.json
          mode: feature
